# Module 1 Lab

## Question 1: BMI

Given the equation for calculating Body Mass Index (BMI) is:
Say an individual weighs 150 lbs and is 68 inches tall. What is their BMI?
𝐵𝑀𝐼 =
weight in pounds × 703
height in inches
2


In [1]:
wt= 150
ht= 68
bmi= (wt*703)/(ht*ht)
print('BMI: ',bmi)

BMI:  22.80493079584775


## Question 2: Math Library


1. Import the math library.
2. Find a function within the math library that will compute the square root of 14 × 0.51
3. Find a function with the math library that will compute 3.25 ^ 2.784 . Now compute this with a simple math
operator provided by standard Python

In [2]:
import math 
math.sqrt(14*0.51)

2.6720778431774774

In [3]:
math.pow(3.25,2.784)

26.61235308864194

In [4]:
print(3.25**2.784)

26.61235308864194


## Question 3: Cost of Pizza

Say you have a 12” diameter pizza. And given the area of a circle is , compute the area of
the pizza and assign that value to the variable area . Now say the cost of the pizza was $8. Compute the cost
per square inch of this pizza. **Hint**: the `math` library contains a `pi` object to use as .
𝐴 = 𝜋(diameter/2)^2


In [5]:
#AREA OF 12 INCH PIZZA - 8$
from math import pi

diameter= 12
A = pi*(diameter/2)**2

print('The area of 12inch pizza: ',A)

The area of 12inch pizza:  113.09733552923255


In [6]:
#AREA OF 15 INCH PIZZA - 12$

diameter= 15
A = pi*(diameter/2)**2

print('The area of 15inch pizza: ',A)

The area of 15inch pizza:  176.71458676442586


#### Now say you have the option to buy the above pizza or a 15" pizza that costs $12. Which is a better deal?

The 15 inch pizza is a better deal because cost per inch for this pizza costs 25 cents less than the 12 inch pizza

## Question 4: Conditional Statements and Snakes

Given the variable language which contains a string, use if/elif/else to write a program that:

returns “I love snakes!” if language is "python" (any kind of capitalization)

returns “Are you a pirate?” if language is "R" (any kind of capitalization)

returns “What is language?” if language is anything else

In [7]:
language = 'PYTHON'

if language.lower() == 'python':
    print('I love snakes!')
elif language.lower() == 'r':
    print('Are you a pirate?')
else:
    print('What is language?')

I love snakes!


## Question 5: Analyzing a Vector of Weights


1. Create a list called weight containing the weight (in kg) of 10 children: 69, 62, 57, 59, 59, 64, 56, 66, 67, 66.

In [8]:
weight =[69, 62, 57, 59, 59, 64, 56, 66, 67, 66]

2. Try and convert these weights to pounds using (1kg = 2.20462lbs). If you try weight * 2.20462 what
results?

IT GIVES US A TYPE ERROR WHERE YOU CAN'T MULTIPLY SEQUENCE BY NON INT OF TYPE 'FLOAT'

In [9]:
# run the below code by removing the comment to see the error

#weight*2.20462

3. Import the numpy library and use the alias np .

4. Now convert weight to an array with np.array() .

5. Now try and convert the array of weights to pounds using weight * 2.20462 what results?


In [10]:
#3 
import numpy as np

#4
weight= np.array(weight)
weight

array([69, 62, 57, 59, 59, 64, 56, 66, 67, 66])

In [11]:
weight.mean()

62.5

In [12]:
weight.sort()
weight

array([56, 57, 59, 59, 62, 64, 66, 66, 67, 69])

In [13]:
#5
lbs=weight*2.20462
lbs

array([123.45872, 125.66334, 130.07258, 130.07258, 136.68644, 141.09568,
       145.50492, 145.50492, 147.70954, 152.11878])

In [14]:
lbs.mean()

137.78875

## Question 6: Back to BMI


Say we have the following height (in inches) for our 10 children: 62, 58, 61, 61, 59, 64, 63, 61, 60, 62. Use the
weights from the last execise and these height values to compute the BMI for each child. What is the average
BMI across all the children?

In [15]:
height= [62, 58, 61, 61, 59, 64, 63, 61, 60, 62]
height= np.array(height)
height

array([62, 58, 61, 61, 59, 64, 63, 61, 60, 62])

In [16]:
lbs

array([123.45872, 125.66334, 130.07258, 130.07258, 136.68644, 141.09568,
       145.50492, 145.50492, 147.70954, 152.11878])

In [17]:
bmi= (lbs*703)/ (height*height)
bmi

array([22.57842876, 26.26079905, 24.57431436, 24.57431436, 27.60429972,
       24.21637281, 25.77222443, 27.48991098, 28.84439073, 27.81984972])

In [18]:
bmi.mean()

25.973490493310617

## Question 7: Nested Dictionary


Given this nest dictionary, extract the element containing the word “BANA”

In [19]:
d = {
 "a_list": [1, 2, 3,],
 "a_dict": {"first": ["this", "is", "inception"],
 "second": [1, 2, 3, "BANA"]}
}

In [20]:
d["a_dict"]["second"][3]

'BANA'

## Question 8: Sorting Arrays


Lets create 20 random integers where the values are randomly created from the value range of 50-100. We'll say
these random integers represent the weight of 20 children. We'll use numpy to generate these numbers. Be
sure to use seed(123) so we get the same results.

In [21]:
from numpy.random import seed
from numpy.random import randint
# seed random number generator
seed(123)
# generate 20 random numbers between 50-100
weights = randint(low=50, high=100, size=20)
weights

array([95, 52, 78, 84, 88, 67, 69, 92, 72, 83, 82, 99, 97, 59, 82, 96, 82,
       97, 75, 69])

In [22]:
weights.sort()
weights

array([52, 59, 67, 69, 69, 72, 75, 78, 82, 82, 82, 83, 84, 88, 92, 95, 96,
       97, 97, 99])

Identify the weights of the three children that have the lightest weight values. Hint: figure out how to sort these
values in ascending order and index the first three values.


In [23]:
weights[0:3]

array([52, 59, 67])

## Question 9: The Zen of Python


Run the following code. Read and embrace this mantra throughout this class and your Python code-writing
lives!

In [24]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
